import top_requested_url
import top_error_generating_url

def menu():
    print("Welcome to the CLI Log Analyzer!")
    print("Please select an option:")
    print("1. Find the top requested URL")
    print("2. Most error is generated by which Url and its count")
    print("3. Exit")

    choice = input("Enter your choice: ")

    if choice == '1':
        file_path = input("Enter the path to the CSV file: ")
        analyzer = top_requested_url.TopRequestedURL(file_path)
        analyzer.fetch_top_requested_url()
    if choice == '2':
        file_path = input("Enter the path to the CSV file: ")
        analyzer = top_error_generating_url.TopErrorGeneratingURL(file_path)
        analyzer.show_result()
    elif choice == '3':
        print("Exiting the program.")
        exit()
    else:
        print("Invalid choice. Please try again.")
        menu()

menu()
